# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 31cdb2e
_src_path: https://gitlab.com/gemseo/dev/copier-gemseo
author_email: contact@gemseo.org
author_name: Matthias De Lozzo
gemseo_min_version: '5'
package_is_a_gemseo_plugin: true
project_is_open_source: true
project_name: gemseo-umdo
project_name_suffix: umdo
project_slug: gemseo_umdo
short_description: Robust MDO and advanced UQ with GEMSEO.
use_gemseo_develop: true
