# Copyright 2021 IRT Saint Exupéry, https://www.irt-saintexupery.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License version 3 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
"""Scenarios to address multidisciplinary design problems under uncertainty."""

from __future__ import annotations

from functools import partial
from types import SimpleNamespace
from typing import TYPE_CHECKING
from typing import Any
from typing import ClassVar

from gemseo.core.function.array_function import ArrayFunction
from gemseo.util.constant import read_only_empty_dict
from gemseo.util.string import MultiLineString
from gemseo.util.string import pretty_str

from gemseo_umdo.disciplines.utils import create_noising_discipline_chain
from gemseo_umdo.formulations.factory import UMDO_FORMULATION_FACTORY

if TYPE_CHECKING:
    from collections.abc import Mapping
    from collections.abc import Sequence

    from gemseo.discipline import Discipline
    from gemseo.formulation.core.base_mdo import BaseMDOFormulation
    from gemseo.formulation.core.base_settings import BaseFormulationSettings
    from gemseo.scenario import EvaluationScenario
    from gemseo.space import DesignSpace
    from gemseo.space import RandomSpace
    from gemseo.util.typing import StrKeyMapping

    from gemseo_umdo.formulations.base_umdo_formulation import BaseUMDOFormulation
    from gemseo_umdo.formulations.base_umdo_formulation_settings import (
        BaseUMDOFormulationSettings,
    )
    from gemseo_umdo.formulations.factory import UMDOFormulationsFactory


class BaseUScenario:
    """Base scenario for multidisciplinary design problems under uncertainty."""

    _formulation_factory: ClassVar[UMDOFormulationsFactory] = UMDO_FORMULATION_FACTORY

    formulation: BaseUMDOFormulation

    def __init__(
        self,
        disciplines: Sequence[Discipline | EvaluationScenario],
        design_space: DesignSpace,
        uncertain_space: RandomSpace,
        statistic_estimation_settings: BaseUMDOFormulationSettings,
        uncertain_design_variables: Mapping[
            str, str | tuple[str, str]
        ] = read_only_empty_dict,
        name: str = "",
        formulation_settings: BaseFormulationSettings | None = None,
        default_input_data: StrKeyMapping = read_only_empty_dict,
    ) -> None:
        """
        Args:
            disciplines: The disciplines.
            design_space: The design space.
            uncertain_space: The uncertain variables
                with their probability distributions.
            statistic_estimation_settings: The settings
                of the statistics' estimation technique.
            uncertain_design_variables: This argument facilitates
                the definition of uncertain design variables in two ways.
                The first way consists of passing a dictionary
                of the form `{"x1": ("+", "u1"), "x2": ("*", "u2"), ...}`
                which defines the uncertain design variables as
                `x1 = dv_x1 + u1` and `x2 = dv_x2 * (1 + u2)`.
                Here `"x1"` and `"x2"` are the names of the design variables
                made uncertain by the random variables `"u_1"` and `"u_2"`
                which typically have zero mean.
                `"x1"` and `"x2"` are the names of the design variables
                actually used in `disciplines`
                while the names `"dv_x1"` and `dv_x2` are generated by the scenario.
                More generally,
                the first element of the tuple is assumed
                to be either the class name or the
                [SHORT_NAME][gemseo_umdo.disciplines.base_noiser.BaseNoiser.SHORT_NAME]
                of a
                [BaseNoiser][gemseo_umdo.disciplines.base_noiser.BaseNoiser]
                (feel free to create new noising disciplines).
                The second way of defining these uncertain design variables
                consists of passing a set of more complex expressions
                of the form `{"x": "{} + u", ...}`
                where `"x"` is the name of the design variable
                actually used in the equations,
                `"u"` is the name of the uncertain variable
                defined in the `uncertain_space`
                and `"{}"` is the optimization variable.
                Leave `"{}"` as is; it will be automatically replaced by `"dv_x"`.
                This more complex format assumes variables of dimension 1.
                If empty,
                do not consider other variable relations
                than those defined by `disciplines`.
            name: The name to be given to the scenario.
                If empty, use the name of the class.
            formulation_settings: The settings of the MDO formulation
                generating the functions evaluable over the uncertain space.
                If `None`,
                use [MDF_Settings][gemseo.formulation.mdf_settings.MDF_Settings].
            default_input_data: Some default input data of the disciplines.
        """  # noqa: D205 D212 D415
        disciplines = list(disciplines)
        if uncertain_design_variables:
            noising_discipline_chain = create_noising_discipline_chain(
                design_space, uncertain_design_variables
            )
            disciplines.insert(0, noising_discipline_chain)

        # The U-MDO formulation requires arguments
        # that the scenario does not pass to the factory of formulations.
        self._formulation_factory = SimpleNamespace(
            create=partial(
                self._formulation_factory.create,
                uncertain_space=uncertain_space,
                mdo_formulation_settings=formulation_settings,
            )
        )
        try:
            super().__init__(
                disciplines,
                design_space,
                name=name,
                formulation_settings=statistic_estimation_settings,
                default_input_data=default_input_data,
            )
        finally:
            del self._formulation_factory

    def add_objective(
        self,
        output_names: str | Sequence[str],
        statistic_name: str,
        minimize: bool = True,
        objective_name: str = "",
        **statistic_parameters: Any,
    ) -> None:
        """Set the objective.

        Args:
            output_names: The names of the outputs used as objective.
            statistic_name: The name of the statistic
                to be applied to the objective, e.g. "Margin".
            minimize: Whether to minimize the statistic of the objective.
            objective_name: The name of the objective to be stored.
                If empty,
                the name is generated from `output_names` and `statistic_name`.
            **statistic_parameters: The parameters of the statistic
                to be applied to the objective,
                e.g. `factor=2.` when `statistic_name="Margin"`.
        """
        problem = self.formulation.problem
        problem.objective = self.formulation.create_objective(
            output_names,
            statistic_name,
            objective_name=objective_name,
            minimize=minimize,
            **statistic_parameters,
        )
        problem.minimize_objective = minimize

    @property
    def formulation_name(self) -> str:  # noqa: D102
        return self.formulation.name

    def add_constraint(
        self,
        output_name: str | Sequence[str],
        statistic_name: str,
        constraint_type: ArrayFunction.ConstraintType = (
            ArrayFunction.ConstraintType.INEQ
        ),
        constraint_name: str = "",
        value: float = 0,
        positive: bool = False,
        **statistic_parameters: Any,
    ) -> None:
        """
        Args:
            statistic_name: The name of the statistic
                to be applied to the constraint, e.g. "margin".
            statistic_parameters: The parameters of the statistics
                to be applied to the constraint,
                `{"factor": 2.}` when `objective_statistic="margin"`.
        """  # noqa: D205 D212 D415
        self.formulation.add_constraint(
            output_name,
            statistic_name,
            constraint_type=constraint_type,
            constraint_name=constraint_name,
            value=value,
            positive=positive,
            **statistic_parameters,
        )

    def add_observable(
        self,
        output_names: Sequence[str],
        statistic_name: str,
        observable_name: str = "",
        discipline: Discipline | None = None,
        **statistic_parameters: Any,
    ) -> None:
        """
        Args:
            statistic_name: The name of the statistic
                to be applied to the constraint, e.g. "margin".
            statistic_parameters: The parameters of the statistics
                to be applied to the constraint,
                `{"factor": 2.}` when `objective_statistic="margin"`.
        """  # noqa: D205 D212 D415
        self.formulation.add_observable(
            output_names,
            statistic_name,
            observable_name=observable_name,
            discipline=discipline,
            **statistic_parameters,
        )

    def __repr__(self) -> str:
        msg = MultiLineString()
        msg.add(self.name)
        msg.indent()
        msg.add(
            "Disciplines: {}",
            pretty_str(self.disciplines, delimiter=" ", use_and=False),
        )
        msg.add("Formulation:")
        msg.indent()
        msg.add("MDO formulation: {}", self.mdo_formulation.__class__.__name__)
        msg.add("Statistic estimation: {}", self.formulation.__class__.__name__)
        msg.dedent()
        msg.add("Uncertain space:")
        msg.indent()
        for line in str(self.uncertain_space).split("\n")[1:]:
            msg.add(line)
        return str(msg)

    @property
    def uncertain_space(self) -> RandomSpace:
        """The uncertain variable space."""
        return self.formulation.uncertain_space

    @property
    def mdo_formulation(self) -> BaseMDOFormulation:
        """The MDO formulation over the uncertain space."""
        return self.formulation.mdo_formulation

    @property
    def available_statistics(self) -> list[str]:
        """The names of the available statistics."""
        return self.formulation.available_statistics
